### PR TITLE
Compatible with Symfony 2.8, PHP 7 and Guzzle 5

### PR DESCRIPTION
**Pull request by RubenHarms**
- Version contraints changed in composer.json
- Resolved some deprecations

### CODE REVIEW

**Comment by DRvanR** [comment]
Hello!

First of all, thanks for the PR and sorry for not getting back sooner. It looks good, however I've got a few questions:

- why is Symfony limited to 2.x? Being compatible with 2.8 without warnings means you are 3.0 compatible, so perhaps that constraint is a bit too tight?
- I assume that a guzzle interface that is used has changed between 5.x and 6.x as guzzle is specified to require <6.0? Would it be feasible to support >= 6.0 as well with some small changes?

Thanks!

**Comment by RubenHarms** [comment]
Hi Daan,

- I was not able to upgrade my software  to 3.0 (a lot of dependencies were not 3 ready), so i can't guarantee it, because i never tested in 3.0. But theoretical it should work.

- As far as I know the current code is not compatible with 6.0 (6 has major changes).  But ofcourse with some small changes that's fixed again. At least the specified versions are compatible now.  Maybe we can work on that in another commit/release? An disadvertage is that we loose support for older versions. I suggest a new release for that.

**Comment by DRvanR** [comment]
Cheers, totally agree :+1:

**Comment by DRvanR** [comment]
This has been included in new release 2.2.0

**Comment by RubenHarms** [comment]
Thanks! (Top, bedankt man)

**Pull request merged**
