### PR TITLE
use latest stable instead of 1.0

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by OskarStark** [comment]
Please merge, thanks

**Comment by OskarStark** [comment]
Any news?

**Comment by OskarStark** [comment]
Is this bundle still maintained?

**Comment by pmeulen** [comment]
Hi Oskar,

We didn't notice your PR, sorry. We'll pick it up. To answer your question: yes, this bundle is still maintained.

**Comment by OskarStark** [comment]
Thank you

Pieter van der Meulen <notifications@github.com> schrieb am Fr. 2. Aug.
2019 um 09:10:

**Comment by pablothedude** [comment]
@OskarStark thanks for the contribution, I will merge your change back.

**Comment by OskarStark** [comment]
Thank you

**Pull request merged**
